openapi: 3.0.0
info: 
  title: Api Rest For Challenge Eldorado
  version: 1.0.0
  schemas:
    Categories:
      type: object
      properties:
        name:
          type: string
      example:
            name: daniloscipioni
           

    
    
